name = "GTAPdata"
uuid = "130c15d4-ad42-4bd4-91d3-6787eb393e58"
authors = ["Henry Chen <chenyh@mit.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CSVtoDIC = "cf815f9a-3c92-448a-b56b-77b95c7ee9f9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[sources]
CSVtoDIC = {rev = "master", url = "https://github.com/chenyhmitedu/CSVtoDIC"}
